name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make install
    - name: chmod x tohtml.sh
      run: chmod +x tohtml.sh
    - name: chmod x index.sh
      run: chmod +x index.sh
#    - name: make
#      run: make index.html
#      timeout-minutes: 60
    - name: a
      run: mkdir ./public
    - name: b
      run: cp index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
